phosphorjs/phosphor

- .travis.yml
> Feature travis

- .travis.yml
- gulpfile.js
Ok, first baby step, this **should** build the `/api/` path of the docs website, and deploy it.
> try to autobuild docs on phosphor

- .travis.yml
Sorry, getting things right on travis is often an iterative process as local env is always different.
> Don't actually create docs before clonign repo

- .travis.yml
> supress git warning message, and use token on ghpages

- examples/chatapp/chat/ichatclient.ts
- examples/chatapp/chat/ichatserver.ts
- src/di/container.ts
- src/di/icontainer.ts
- src/di/token.ts
- src/shell/ipluginlist.ts
- src/shell/ishellview.ts
a cleaner way to create run-time type tokens
> use a Token class instead of interface

- src/widgets/dockarea.ts
- src/widgets/layoutengine.ts
- src/widgets/menu.ts
Howdy, as per usual... no major issues :)
> Minor typos in doc comments.

- test/src/index.ts
- test/src/ui/boxengine.spec.ts
- test/src/ui/title.spec.ts
```
ui/            |      100 |      100 |      100 |      100 |                |
boxengine.js  |      100 |      100 |      100 |      100 |                |
title.js      |      100 |      100 |      100 |      100 |                |
All files       |    99.05 |    93.94 |    98.87 |    99.34 |                |
> Boxengine and Title tests

- test/src/index.ts
- test/src/ui/widget.spec.ts
Adds tests for `widget.ts`
```
widget.js     |    99.22 |    90.07 |      100 |    99.73 |            892 |
```
> Widget tests

- test/src/index.ts
- test/src/typings.d.ts
- test/src/ui/commands.spec.ts
```
commands.js   |      100 |      100 |      100 |      100 |                |
> Commands tests

- src/ui/menu.ts
- test/src/index.ts
- test/src/typings.d.ts
- test/src/ui/menu.spec.ts
```
menu.js       |    96.53 |    91.35 |      100 |    96.49 |... 4,1431,1449 |
```
> Menu tests

- test/src/index.ts
- test/src/ui/panel.spec.ts
```
panel.js      |      100 |    90.91 |      100 |      100 |                |
```
> Panel tests

- src/ui/menubar.ts
- test/src/index.ts
- test/src/typings.d.ts
- test/src/ui/menubar.spec.ts
```
menubar.js    |    98.53 |    90.37 |      100 |     98.5 |... 589,590,595 |
```
> MenuBar tests

- test/src/index.ts
- test/src/ui/boxpanel.spec.ts
```
boxpanel.js   |    99.25 |    89.41 |      100 |    99.24 |        329,340 |
```
> Boxpanel tests

- package.json
- test/src/index.ts
- test/src/ui/splitpanel.spec.ts
```
splitpanel.js |    98.28 |    89.86 |      100 |    98.25 |... 964,997,998 |
```
> SplitPanel tests

- test/src/index.ts
- test/src/ui/stackedpanel.spec.ts
```
------------------|----------|----------|----------|----------|----------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------|----------|----------|----------|----------|----------------|
stackedpanel.js |    98.45 |    85.37 |      100 |    98.41 |        159,170 |
```
> StackedPanel tests

- src/ui/tabbar.ts
- test/src/index.ts
- test/src/ui/tabbar.spec.ts
```
tabbar.js     |    96.86 |    82.66 |      100 |    96.82 |... 80,781,1044 |
```
> TabBar tests

- test/src/index.ts
- test/src/ui/tabpanel.spec.ts
```
------------------|----------|----------|----------|----------|----------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------|----------|----------|----------|----------|----------------|
tabpanel.js     |      100 |    84.21 |      100 |      100 |                |
```
> TabPanel tests

- package.json
- scripts/travis_after_success.sh
- scripts/travis_script.sh
Typedoc `0.4.2` was released yesterday.
> Reinstate docs build

- package.json
- test/src/ui/splitpanel.spec.ts
- test/src/ui/stackedpanel.spec.ts
- test/src/ui/tabbar.spec.ts
Fixes #80, fixes #84, fixes #85
> Fix IE test failures

- src/collections/vector.ts
- src/ui/boxpanel.ts
- src/ui/commandpalette.ts
- src/ui/keymap.ts
- src/ui/menu.ts
- src/ui/menubar.ts
- src/ui/panel.ts
- src/ui/splitpanel.ts
- src/ui/tabbar.ts
- test/src/collections/vector.spec.ts
> Replace vector remove(index) with remove(value) and popAt(index)

- src/ui/keymap.ts
- test/src/ui/keymap.spec.ts
> Allow keymap manager to accept a command registry

- src/ui/menu.ts
- test/src/ui/menu.spec.ts
- test/src/ui/menubar.spec.ts
> Allow custom keymap and commands in menus

- package.json
- test/src/dom/dragdrop.spec.ts
- test/src/index.ts
```
--------------------|----------|----------|----------|----------|----------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------|----------|----------|----------|----------|----------------|
dragdrop.js       |    96.86 |    89.47 |      100 |    96.86 |... 593,625,635 |
```
> Dragdrop tests

- src/collections/vector.ts
- src/ui/boxpanel.ts
- src/ui/commandpalette.ts
- src/ui/menu.ts
- src/ui/menubar.ts
- src/ui/panel.ts
- src/ui/splitpanel.ts
- src/ui/tabbar.ts
- test/src/collections/vector.spec.ts
- test/src/ui/commandpalette.spec.ts
- test/src/ui/menu.spec.ts
- test/src/ui/menubar.spec.ts
- test/src/ui/panel.spec.ts
- test/src/ui/tabbar.spec.ts
> update removal apis

- src/dom/query.ts
- test/karma-cov.conf.js
- test/karma.conf.js
- test/src/dom/query.spec.ts
still needs tests and verification
> follow spec-ish for scroll into view

- src/ui/tabbar.ts
- styles/base.css
> fixes #130

- test/src/index.ts
- test/src/ui/focustracker.spec.ts
> Add tests for focustracker

- test/src/index.ts
- test/src/ui/vdom.spec.ts
```
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
vdom.js |    99.67 |    87.07 |      100 |    99.67 |            702 |
```
> Add tests for vdom

- @phosphor/application/src/index.ts
> add optional services to plugin

- @phosphor/dragdrop/src/index.ts
> add drag scroll support

- packages/signaling/src/index.ts
- tests/test-signaling/src/index.spec.ts
This adds a `disconnectBetween` function which is new functionality which severs all connections between a specific sender and specific receiver.
This also adds a `disconnectAll` function which is *currently* the same functionality as `clearData`, but it makes for a symmetric API with the other functions, and allows for `clearData` to do other things in the future if the signal data stored for a given object grows beyond simply connections.
@akosyakov @blink1073 @afshin
> fix #215 by adding a `disconnectBetween` function

- packages/application/src/index.ts
- packages/coreutils/src/index.ts
- packages/coreutils/src/token.ts
- tests/test-coreutils/src/index.spec.ts
- tests/test-coreutils/src/token.spec.ts
> Move Token class to coreutils. Fixes #231.

- packages/widgets/src/dockpanel.ts
> add a layoutModified signal to the dock panel

- packages/messaging/src/index.ts
- packages/signaling/src/index.ts
- tests/test-messaging/src/index.spec.ts
- tests/test-signaling/src/index.spec.ts
- tests/test-signaling/tsconfig.json
> add signal exception handler

- examples/example-dockpanel/src/index.ts
- packages/commands/src/index.ts
- packages/widgets/src/menu.ts
- packages/widgets/src/menubar.ts
- packages/widgets/src/tabbar.ts
- packages/widgets/src/title.ts
Fixes #260 (using alternative solution)
cc @birdsarah
> add icon label support and rename  ->  with a deprecated alias shim

- packages/commands/src/index.ts
> fixes #333

- packages/commands/src/index.ts
> more explict wildcard

- packages/datagrid/src/graphicscontext.ts
The value seems to be inverted.
> Fix GraphicsContext.isDisposed

- packages/datastore/src/textfield.ts
Slice vs splice signature difference.
> Bugfix: Datastore textfield apply patch removing characters

- .travis.yml
- lerna.json
- package.json
- yarn.lock
> Upgrade Lerna and separate version bump from publish

- packages/widgets/src/layout.ts
> Comment typo: Ajdust -> Adjust

- GOVERNANCE.md
- README.md
This pull request adds @afshin and @blink1073 as maintainers for every PhosphorJS package, in line with the new governance model.
> Add Darian and Steve as package maintainers.

- .gitignore
- .travis.yml
- packages/datastore/src/datastore.ts
- packages/datastore/src/listfield.ts
- packages/datastore/src/schema.ts
- packages/datastore/src/textfield.ts
- tests/test-datastore/karma.conf.js
- tests/test-datastore/package.json
- tests/test-datastore/src/datastore.spec.ts
- tests/test-datastore/src/fields.spec.ts
- tests/test-datastore/src/index.spec.ts
- tests/test-datastore/src/listfield.spec.ts
- tests/test-datastore/src/mapfield.spec.ts
- tests/test-datastore/src/registerfield.spec.ts
- tests/test-datastore/src/table.spec.ts
- tests/test-datastore/src/textfield.spec.ts
- tests/test-datastore/tsconfig.json
- tests/test-datastore/webpack.config.js
This does two major things:
1. Implements the cemetery for listfields and textfields. There are some reasonably significant changes to the implementation of patching for those fields, so some scrutiny there would be good.
2. Adds a test suite. There are always more to add, but I think the current set is reasonably good, and could use some review.
> Feature tables3 testing

- examples/example-datagrid/src/index.ts
- packages/datagrid/src/basickeyhandler.ts
- packages/datagrid/src/basicselectionmodel.ts
- packages/datagrid/src/datagrid.ts
- packages/datagrid/src/selectionmodel.ts
- packages/domutils/src/clipboard.ts
- packages/domutils/src/index.ts
This implements copy-to-system-clipboard of the current selection.
The behavior is configurable wrt element separator, to-string formatting, which headers are included in the copy, and cell count threshold above which a warning dialog is displayed warning the user that the copy may take awhile.
CC @afshin @blink1073 @ellisonbg @jasongrout @SylvainCorlay
> Feature datagrid copy
