- .travis.yml
Ok... now auth is used but refused, I think I stored the credentials in the wrong git directory, so it finds an empty token, and this should fix it I hope. 
Once again it works locally, but I'm not sure how to know wether the setup is right, or if it uses my local SSH key.
I've deployed manually in the meantime so http://phosphorjs.github.io/docs/ give you the docs.
> move credentials

- .travis.yml
Should make the following page works.
http://phosphorjs.github.io/examples/
There should be a way to actually wrap the `index.ts` and `index.html` in pre-blocks to actually make the examples readables.
> build example for doc site

- src/core/mimedata.ts
- test/src/core/mimedata.spec.ts
- test/src/index.ts
```
--------------------|----------|----------|----------|----------|----------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------|----------|----------|----------|----------|----------------|
mimedata.js       |      100 |      100 |      100 |      100 |
```
> Add tests for mimedata

- src/ui/menu.ts
- src/ui/menubar.ts
- src/ui/tabpanel.ts
- src/ui/widget.ts
- test/src/ui/menu.spec.ts
- test/src/ui/tabpanel.spec.ts
- test/src/ui/widget.spec.ts
We deemed `focus/blur` to be the wrong semantic action, and instead decided to use `activate/deactivate`, where the default action is to focus/blur the widget.  
This also makes the messages conflatable.
> Replace widget focus/blur with activate/deactivate

- src/algorithm/mutation.ts
- src/algorithm/searching.ts
- src/core/signaling.ts
- src/dom/cursor.ts
- src/dom/sizing.ts
Fixes all references to `phosphor-ui` and `phosphor-core` in the library.
cf #50.
> Clean up path references in examples

- src/ui/commandpalette.ts
- test/src/ui/commandpalette.spec.ts
cf #50.
The `CommandItem` would also need to expose its `keymap` and `commands` so we can verify compatibility with the palette.  This could all be avoided if we only accepted options to create a command item, but you'd lose the ability to make custom items.
> Allow custom command registry and keymap in command palette

- package.json
Used to "Tell people where the bulk of your library is. Nothing special is done with the lib folder in any way, but it's useful meta info."
https://docs.npmjs.com/files/package.json#directorieslib
We plan to use this in JupyterLab as the place to look for source files if a `main` is not given.
cf https://github.com/jupyter/jupyterlab/issues/224#issuecomment-241551346
> Add directories.lib config to package.json

- src/ui/menu.ts
Deleting undefined properties raises an error in Safari
[Docs suggest](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/delete) that deleting should raise in some cases in strict mode, but Safari is the only browser that seems to raise for this particular case. I can't actually tell if the documented case for raising should apply or not.
cf jupyter/jupyterlab#749
> only delete node.dataset['command'] if defined

- @phosphor/widgets/src/menu.ts
This was preventing submenus at index 1 from opening.  cf https://github.com/jupyterlab/jupyterlab/issues/1799.
> Fix initial value for menu child index

- examples/example-dockpanel/src/index.ts
- packages/widgets/src/docklayout.ts
- packages/widgets/src/dockpanel.ts
This implements save/restore dock layout. Fixes #33.
The only thing I'm not sure about is the top level layout object. Currently it's a simple object with one `main` property which holds the layout config for the main area. The thinking here is that if we expand dock layout support to maximized panels and/or tear-out panels, then we'll need space to grow extra properties. However, @ellisonbg and I talked at length today, and were thinking that such feature may end up not being necessary, because there are better ways to implement a similar experience. In that case, we can ditch the container object, and the `main` property value could be the value of interchange.
cc @ellisonbg @jasongrout @blink1073 @afshin
> Feature save restore layout

- examples/example-dockpanel/src/index.ts
- packages/widgets/src/docklayout.ts
- packages/widgets/src/dockpanel.ts
> add a type-safe version string to dock layout config. fixes #228

- examples/example-dockpanel/src/index.ts
- packages/widgets/src/contextmenu.ts
- packages/widgets/src/index.ts
This implements universal context menus. The gif below shows the context menu being launched from right-clicking on various widgets. The CSS selectors for the menu items control which items are shown the menu. When clicking near the tab bar, no menu items are matched, so the application instead shows the default browser context menu. *The ContextMenu object does not make this decision for you, it is up to the application to decide if/when to show the browser menu or custom context menu. The ContextMenu object returns `false` from its `open` method when there are no matching items. The example here uses that flag to decide whether to show the default browser menu.* 
cc @ellisonbg @jasongrout @blink1073 @afshin
> Feature universal context menus

- packages/widgets/src/contextmenu.ts
This should fix corner cases found in: https://github.com/jupyterlab/jupyterlab/pull/2055
> more robust handling of node matching

- examples/example-dockpanel/src/index.ts
- packages/algorithm/src/string.ts
- packages/widgets/src/commandpalette.ts
- tests/test-algorithm/src/string.spec.ts
- tests/test-widgets/src/commandpalette.spec.ts
Closes #262
Fixes https://github.com/jupyterlab/jupyterlab/issues/1182
> Feature improve fuzzymatch

- examples/example-datagrid/src/index.ts
- packages/datagrid/package.json
- packages/datagrid/src/index.ts
- packages/datagrid/src/jsondatamodel.ts
This adds a concrete data model based on the following:
* Record oriented JSON data.
* An associated JSON Table Schema (https://specs.frictionlessdata.io/table-schema/#field-descriptors).
Lots more to work on here, but at least this gets us started. I have to switch gears to other stuff, feel free to take over the PR or merge and iterate.
Some additional complications we will need to deal with eventually:
* The different type/format combination that are possible and how to render them.
* Multiple column headers that show up with a column MultiIndex in Pandas.
> Add JSON data model

- packages/widgets/src/dockpanel.ts
Fixes #360.
This restores the tab drop zone to the dock panel. The top root drop zone is also shrunk in order to conflict less with the top tab bar.
I've provided two options for the overlay: the first one adds the overlay of the same shape as the tab zone. The second one adds the overlay of the same shape as the center-drop-zone overlay. I'd appreciate thoughts about which one is better.
cc @jasongrout @blink1073 @tgeorgeux @ellisonbg
> Restore tab drop zone

- GOVERNANCE.md
- README.md
@sccolbert @jasongrout @blink1073 @afshin @ian-r-rose @vidartf @saulshanabrook
This is an initial governance model for phosphor. @sccolbert and I have gone over this in a call.
Once this has been reviewed and merged, and an initial group of Package Maintainers are appointed, there are a number of outstanding questions to tackle, that we wanted to get the PM's input on:
- Determine response times for PRs and issues.
- How long to wait for CE vetos?
- Process around CE stepping down, electing a new one?
- How long do we give package maintainers to create initial tutorial documentation?
- How to manage GitHub milestones?
- How many votes are needed for a quorum?
* Suggestion: 100% expected unless unable due to emergency. Votes are subject to a time limit (tbd). Maintainers missing a vote due …
> Initial governance model and principles for phosphor

- packages/widgets/style/commandpalette.css
This fixes overflow behavior for command palette items so that long labels are truncated with ellipses.
> Don't overflow item content

- packages/disposable/package.json
- packages/disposable/src/index.ts
- packages/disposable/tests/src/index.spec.ts
- packages/disposable/tests/tsconfig.json
- packages/disposable/tsconfig.json
- packages/widgets/src/widget.ts
This PR adds:
* An `IObservableDisposable` interface that extends the `IDisposable` by adding a `disposed` signal that emits when the object is disposed.
* An `ObservableDisposableDelegate` that extends the `DisposableDelegate` with a `disposed` signal.
* An `ObservableDisposableSet` that extends the `DisposableSet` with a `disposed` signal.
* Tests for the two new classes.
The name "observable delegate" is quite long. If you can think of a shorter name, please do.
> Add observable disposable interface, delegate, and set. 

- packages/application/src/index.ts
Fixes #389 by including optional dependencies in the plugin cycle check.
> Include optional dependencies in cycle check

- packages/widgets/src/dockpanel.ts
Our heuristic is that if a descendant of the dock panel will handle the drop, it will also handle drag over events and they won’t bubble up to the dock panel. This makes the dock panel always hide the overlay asynchronously on drag leave, so the hide will be cancelled if a drag over event then immediately bubbles up to the dock panel.
> Clear the dockpanel overlay if a descendant will handle the drop.

- packages/widgets/src/commandpalette.ts
@sccolbert mentioned this attribute should be readonly in a walkthrough of Phosphor code.
> Fix a discriminant type attribute to be readonly

- packages/datastore/src/datastore.ts
- packages/datastore/src/table.ts
- packages/datastore/tests/src/datastore.spec.ts
Allows the state of a datastore to be serialized and restored. Note: The state can only be restored on initialization. Mainly meant to enable checkpoints.
Also includes a simple round-trip test
> Add (de-)serialization to datastore

- examples/example-datagrid/src/index.ts
- packages/datagrid/src/cellrenderer.ts
- packages/datagrid/src/datagrid.ts
- packages/datagrid/src/datamodel.ts
- packages/datagrid/src/graphicscontext.ts
- packages/datagrid/src/index.ts
- packages/datagrid/src/jsonmodel.ts
- packages/datagrid/src/renderermap.ts
- packages/datagrid/src/sectionlist.ts
- packages/datagrid/src/textrenderer.ts
cc @blink1073 @afshin @jasongrout @ellisonbg @SylvainCorlay 
This updates the `DataModel` to allow per-cell `metadata`. I profiled this with the datagrid example app, and found negligible difference in rendering times. This change will make it easier to build a spreadsheet model, where the easiest way to store per-cell type/styling/formatting info is with per-cell metadata.
I also updated the logic of the `RendererMap`. My initial implementation of matching based on metadata string values was too much magic (IMO) and was unnecessarily restrictive. The new version is much simpler and has much more flexibility. It allows for arbitrary resolution logic by the end user.
The `prepare` method was removed from `CellRenderer` because it was called once per column. This matched the mental model …
> implement per-cell metadata. simplify the renderer map.

- packages/datastore/src/listfield.ts
- packages/datastore/src/textfield.ts
- packages/datastore/tests/src/listfield.spec.ts
- packages/datastore/tests/src/textfield.spec.ts
- packages/datastore/tests/tsconfig.json
Using `Array.splice` when the to-be-spliced values can run into browser limits for the most arguments allowed to be passed to a variadic function. This can happen especially when initializing a large text field (i.e., a few hundred thousand characters).
This PR implements an internal utility for splitting up large splices, getting around the browser limitations on the number of function args. The chunk size 100000 comes from some experimentation with Chrome and Firefox.
Now, text files of this size also start running into problems with ID sizes, which we still need to solve. But this is a mostly orthogonal problem.
> Handle long splices for textfield and listfield.

- packages/datastore/package.json
- packages/datastore/src/datastore.ts
- packages/datastore/tsconfig.json
- packages/signaling/src/index.ts
- yarn.lock
This adds some helper utilities for getting, updating, and listening to data in the datastore.
* There are three type aliases for specifying `TableLocation`, `RecordLocation`, and `FieldLocation`.
* There are utility functions that allow you to get/update/listen-to tables, records, and fields. This makes a total of nine utility functions.
* Adds a `Datastore.withTransaction` helper which wraps a callback in `beginTransaction`/`endTransaction`.
These are currently statics in a `Datastore` namespace, since that's how I've been using them in JLab, but some of them could be moved onto the datastore class itself.
> Add datastore helper functions.

- packages/datastore/src/datastore.ts
- yarn.lock
Follow up to #418. This keeps the reference to the datastore separate from the reference to fields, records, and fields.
So instead of the previous data locations specified like
```typescript
loc1 = {
datastore: Datastore;
schema: S;
record: string;
};
loc2 = {
datastore: Datastore;
schema: S;
record: string;
field: string;
};
```
we have something like
```typescript
{
datastore: Datastore;
loc1: {
schema: S;
record: string;
};
loc2: {
schema: S;
record: string;
field: string;
};
}
```
I have found that this works a bit better for more complex compound data models which might need to  contain references to multiple locations in a datastore. For instance, a cell model will need to know the location of its text field, as well as a location to a table of cell outputs. This enforces via the …
> Update datastore helpers 

- packages/datagrid/src/datagrid.ts
I noticed exceptions thrown in shadow rendering code while testing in Internet Explorer. They are caused by these typos.
> fix scroll shadow color typos

- packages/datagrid/src/datagrid.ts
When the selectionMode is the full column/row, it doesn't make sense to highlight the entire orthogonal header.
> Don't do header highlighting when selectionMode is row or column
